### ISSUE TITLE
Integrate peripherals to the project

### ISSUE THREAD

**Issue by fabocode** [fabocode/tst-mcu-firmware#6]
- [x] Integrate FreeRTOS
  - [x] Create light task 
  - [x] Create display task 
- [x] GPIO for Lights 
- [x] LCD over I2C
- [x] 4x4 Keypad
- [x] External Memory
- [x] RTC
- [x] External Interrupts (Pedestrians)

**Comment by fabocode** [comment]
#### Description

The project required to add FreeRTOS to handle two important tasks during the running time in the semaphore OS: Lights task and the LCD GUI interface:
- lightTask
- displayTask

Documentation to get it implemented was specified in this [wiki page](https://github.com/fabocode/tst-mcu-firmware/wiki/FreeRTOS)

**Comment by fabocode** [comment]
I am back to work in this issue. 

Please @ajsb85  take a look to 57ec1f0 and 42be90e where it is placed how the light class is created, I will now create a simple test method to loop over all the light/LEDs selected.

**Comment by fabocode** [comment]
With 7f83d33 we're done with the GPIO for Lights task.

**Comment by fabocode** [comment]
#### Description
For the LCD over I2C task I plan to use a [third party library ](https://github.com/firebull/STM32-LCD-HD44780-I2C) to drive the LCD module using the PCF8574.

#### Tasks
- [x] Turn on I2C in STM32CubeMX at 100KHz mode 
- [x] Turn on DMA
- [x] Turn on Interrupts
- [ ] Develop an LCD class to drive LCD methods
- [ ] Develop a test method to show a demo image in the display

#### Documentation
I already have selected the pins for this task. This will be detailed specified in the [LCD wiki](https://github.com/fabocode/tst-mcu-firmware/wiki/LCD-over-I2C) to reproduce the environment.

**Comment by fabocode** [comment]
#### Description
For the Keypad task it is required to enable several different GPIOs to be able to drive a keypad in the project. 

#### Tasks
- [ ] Set up the GPIO selected for this peripheral
- [ ] Include the [Keypad Library](https://github.com/nimaltd/KeyPad)
- [ ] Modify the library to match with current MCU 
- [ ] Develop the Keypad to drive Keypad methods 
- [ ] Develop a test method to show how the keypad works 

#### Documentation
Hardware and firwmare configuration is detailed in the Keypad wiki page

**Comment by fabocode** [comment]
#### Description
We are going to need an external memory to keep a register of the semaphore schedule. 

For this I ordered the [Microchip Technology AC500100](https://co.mouser.com/ProductDetail/579-AC500100) which came with the EERAM **47L16** which I plan to use for prototyping. 

#### Tasks
- [ ] Develop a class to handle the External Memory over I2C 
- [ ] Write methods to do single read/write to the external memory.

#### Documentation
Hardware and firwmare configuration is detailed in the EERAM wiki page

**Comment by fabocode** [comment]
#### Description
It is necessary to add an RTC to the project in order to show/display current time and date.

The current STM32F411RE comes with a builtin RTC so we are going to take advantage of this feature. 


#### Tasks
- [ ] Add RTC peripheral using the STM32CubeMX.
- [ ] Develop a class for the RTC.
- [ ] Write methods to handle set/get time and date.

#### Documentation
RTC firwmare configuration is detailed in the [RTC wiki page](https://github.com/fabocode/tst-mcu-firmware/wiki/RTC)

**Comment by fabocode** [comment]
#### Description
It is also required to add external interrupts for the pedestrians input. I am still thinking about how should I implement this because interrupts are function that has special treatment:

- they need to execute very quick pieces of code to avoid possible failures during the development 
- This functions do not return any value 
- Are executed by an ISR that is the handler for this situations. 
- Some of this interrupts are related internally and I need to test them to check if they are suitable for our use cases, like they should be able to receive multiple inputs. I am wondering if in the use case that two users press two different pedestrians inputs, they system will only take care of 1 of them. 

#### Tasks
- [ ] Set up the GPIO selected for the external interrupts
- [ ] Test different use cases to check functionality (multiple inputs)
- [ ] Develop a class for the pedestrians object 
- [ ] Write methods to handle pedestrian inputs to the system

**Comment by fabocode** [comment]
According to the previous discussion that we had, I will continue the development of the project without the USB feature to leave it in a future use case to advance with the other milestones that we have, since USB peripheral has some problems integration with FreeRTOS. 

I've read that this is something that the team of ST is working on according to this [source with the same issue](https://community.st.com/s/question/0D50X0000BaLmAJ/setup-freertos-and-usb-host-with-stm32cubeide):
